name: ui_challenges_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.17
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.4.10
  riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # make our assets path clear for easy asset importation
  assets:
    - assets/images/fruits_and_veg_ui/
    - assets/images/garden_planning/
    - assets/images/socials/
    - assets/images/ui/
